# docker-compose.yml para iniciar o LocalStack
version: '3.8'

services:
  localstack:
    container_name: localstack
    # Imagem oficial do LocalStack
    image: localstack/localstack:latest
    ports:
      # Porta "edge" principal para acessar todos os serviços
      - "127.0.0.1:4566:4566"
      # Porta para o dashboard web do LocalStack
      - "127.0.0.1:8080:8080"
    environment:
      # Habilita serviços específicos para economizar recursos.
      - SERVICES=lambda,s3
      # Configuração para modo de depuração (opcional)
      - DEBUG=1
    volumes:
      # Volume para persistir o estado do LocalStack entre reinicializações
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data: